services:
  web:
    image: nginx:${VERSION}
    container_name: workshop-nginx
    ports:
      - "80:80"
    networks:
      - workshop-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      - "com.terraform.workshop=nginx"
      - "com.terraform.workshop.role=webserver"

networks:
  workshop-network:
    external: true  # Use the network created by SQLite stack