services:
  web:
    image: nginx:${VERSION}
    container_name: workshop-nginx
    ports:
      - "80:80"
    networks:
      - workshop-network
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        cat > /etc/nginx/conf.d/default.conf <<'EOF'
        resolver 127.0.0.11 valid=10s;

        server {
            listen 80;
            server_name localhost;

            location / {
                set $$upstream workshop-webapp:3000;
                proxy_pass http://$$upstream;
                proxy_set_header Host $$host;
                proxy_set_header X-Real-IP $$remote_addr;
                proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
            }

            location /health {
                set $$upstream workshop-webapp:3000;
                proxy_pass http://$$upstream/health;
            }
        }
        EOF
        nginx -g 'daemon off;'
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      - "com.terraform.workshop=nginx"
      - "com.terraform.workshop.role=webserver"

networks:
  workshop-network:
    external: true